# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pixelcamm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 480)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 480))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Лёха/.designer/backup/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(11,70,150,255), stop:1 rgba(0,140,255,255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainLabel.setGeometry(QtCore.QRect(400, 0, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mainLabel.setFont(font)
        self.mainLabel.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69))")
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.showCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.showCheck.setGeometry(QtCore.QRect(760, 0, 120, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.showCheck.setFont(font)
        self.showCheck.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.showCheck.setChecked(True)
        self.showCheck.setObjectName("showCheck")
        self.cameraBox = QtWidgets.QComboBox(self.centralwidget)
        self.cameraBox.setGeometry(QtCore.QRect(640, 30, 350, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.cameraBox.setFont(font)
        self.cameraBox.setStyleSheet("border: 1px solid blue;\n"
"border-radius: 5px;")
        self.cameraBox.setCurrentText("")
        self.cameraBox.setObjectName("cameraBox")
        self.recordButton = QtWidgets.QPushButton(self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(640, 430, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recordButton.setFont(font)
        self.recordButton.setStyleSheet("QPushButton{\n"
"    border: 1px solid blue;\n"
"    border-radius: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0     rgba(11,70,150,255), stop:1 rgba(0,140,255,255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0     rgba(111,170,250,255), stop:1 rgba(100,240,255,255));\n"
"}")
        self.recordButton.setObjectName("recordButton")
        self.cameraImage = QtWidgets.QLabel(self.centralwidget)
        self.cameraImage.setGeometry(QtCore.QRect(10, 30, 621, 440))
        self.cameraImage.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: 1px solid blue;")
        self.cameraImage.setMidLineWidth(0)
        self.cameraImage.setText("")
        self.cameraImage.setPixmap(QtGui.QPixmap("bot.gif"))
        self.cameraImage.setScaledContents(True)
        self.cameraImage.setObjectName("cameraImage")
        self.dirpathEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dirpathEdit.setGeometry(QtCore.QRect(640, 100, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dirpathEdit.setFont(font)
        self.dirpathEdit.setStyleSheet("border: 1px solid blue;\n"
"border-radius: 5px;")
        self.dirpathEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dirpathEdit.setObjectName("dirpathEdit")
        self.filepathEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.filepathEdit.setGeometry(QtCore.QRect(640, 220, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filepathEdit.setFont(font)
        self.filepathEdit.setStyleSheet("border: 1px solid blue;\n"
"border-radius: 5px;")
        self.filepathEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.filepathEdit.setObjectName("filepathEdit")
        self.dirpathLabel = QtWidgets.QLabel(self.centralwidget)
        self.dirpathLabel.setGeometry(QtCore.QRect(720, 70, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dirpathLabel.setFont(font)
        self.dirpathLabel.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69))")
        self.dirpathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dirpathLabel.setObjectName("dirpathLabel")
        self.filepathLabel = QtWidgets.QLabel(self.centralwidget)
        self.filepathLabel.setGeometry(QtCore.QRect(720, 190, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filepathLabel.setFont(font)
        self.filepathLabel.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69))")
        self.filepathLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.filepathLabel.setObjectName("filepathLabel")
        self.dirpathButton = QtWidgets.QPushButton(self.centralwidget)
        self.dirpathButton.setGeometry(QtCore.QRect(640, 140, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dirpathButton.setFont(font)
        self.dirpathButton.setStyleSheet("QPushButton{\n"
"    border: 1px solid blue;\n"
"    border-radius: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0     rgba(11,70,150,255), stop:1 rgba(0,140,255,255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0     rgba(111,170,250,255), stop:1 rgba(100,240,255,255));\n"
"}")
        self.dirpathButton.setObjectName("dirpathButton")
        self.formatLabel = QtWidgets.QLabel(self.centralwidget)
        self.formatLabel.setGeometry(QtCore.QRect(640, 260, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.formatLabel.setFont(font)
        self.formatLabel.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69))")
        self.formatLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formatLabel.setObjectName("formatLabel")
        self.formatEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.formatEdit.setGeometry(QtCore.QRect(760, 260, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.formatEdit.setFont(font)
        self.formatEdit.setStyleSheet("border: 1px solid blue;\n"
"border-radius: 5px;")
        self.formatEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.formatEdit.setObjectName("formatEdit")
        self.snapshotButton = QtWidgets.QPushButton(self.centralwidget)
        self.snapshotButton.setGeometry(QtCore.QRect(640, 380, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.snapshotButton.setFont(font)
        self.snapshotButton.setStyleSheet("QPushButton{\n"
"    border: 1px solid blue;\n"
"    border-radius: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0     rgba(11,70,150,255), stop:1 rgba(0,140,255,255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0     rgba(111,170,250,255), stop:1 rgba(100,240,255,255));\n"
"}")
        self.snapshotButton.setObjectName("snapshotButton")
        self.imgformatLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgformatLabel.setGeometry(QtCore.QRect(640, 300, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.imgformatLabel.setFont(font)
        self.imgformatLabel.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69))")
        self.imgformatLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.imgformatLabel.setObjectName("imgformatLabel")
        self.imgformatEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.imgformatEdit.setGeometry(QtCore.QRect(760, 300, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.imgformatEdit.setFont(font)
        self.imgformatEdit.setStyleSheet("border: 1px solid blue;\n"
"border-radius: 5px;")
        self.imgformatEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.imgformatEdit.setObjectName("imgformatEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PixelCamm"))
        self.mainLabel.setText(_translate("MainWindow", "PixelCamm By Pixelsuft"))
        self.showCheck.setText(_translate("MainWindow", "Show preview"))
        self.recordButton.setText(_translate("MainWindow", "Record!"))
        self.dirpathEdit.setText(_translate("MainWindow", "."))
        self.dirpathLabel.setText(_translate("MainWindow", "Folder"))
        self.filepathLabel.setText(_translate("MainWindow", "File Name"))
        self.dirpathButton.setText(_translate("MainWindow", "Select Folder"))
        self.formatLabel.setText(_translate("MainWindow", "Video Format"))
        self.formatEdit.setText(_translate("MainWindow", "mp4"))
        self.snapshotButton.setText(_translate("MainWindow", "Snapshot!"))
        self.imgformatLabel.setText(_translate("MainWindow", "Image Format"))
        self.imgformatEdit.setText(_translate("MainWindow", "png"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
